version: '3.8'

services:
  # --- Servicio Web (Django) ---
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # --- FORZAR HORA COLOMBIA ---
      - TZ=America/Bogota
      # Variables de Base de Datos
      - DB_HOST=db             # <--- IMPORTANTE: Le dice a Docker que use 'db'
      - POSTGRES_DB=paso_beauty_db
      - POSTGRES_USER=paso_user
      - POSTGRES_PASSWORD=paso_password
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - db
      - redis

  # --- Servicio Base de Datos (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    ports:                     # <--- IMPORTANTE: Abre el puerto a Windows
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TZ=America/Bogota      # La base de datos tambiÃ©n en hora Colombia
      - POSTGRES_DB=paso_beauty_db
      - POSTGRES_USER=paso_user
      - POSTGRES_PASSWORD=paso_password
      - POSTGRES_HOST_AUTH_METHOD=trust

  # --- Servicio Cache (Redis) ---
  redis:
    image: redis:7-alpine
    environment:
      - TZ=America/Bogota

volumes:
  postgres_data: