services:
  - type: web
    name: paso-backend
    runtime: docker
    region: oregon
    plan: starter # El plan de $7 USD que mencionaste
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paso-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2" # Optimización básica para tráfico

databases:
  - name: paso-db
    region: oregon
    plan: starter # Base de datos pagada (segura y con backups)
    databaseName: paso_db
    user: paso_admin