services:
  - type: web
    name: paso-backend
    runtime: docker
    region: oregon
    plan: starter      # Corregido (antes era free o starter)
    branch: main
    numInstances: 1
    healthCheckPath: /
    # Este comando es el SEGURO para evitar errores de Timeout:
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 8 --timeout 0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paso-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"

databases:
  - name: paso-db
    region: oregon
    plan: starter      # <--- CORREGIDO: 'basic-256mb' darÃ­a error. Usa 'starter'.
    databaseName: paso_db
    user: paso_admin