services:
  # Servicio Web (Django)
  - type: web
    name: paso-backend
    env: docker
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: paso-db
          property: connectionString

databases:
  # Base de Datos (PostgreSQL)
  - name: paso-db
    databaseName: paso_db
    user: paso_user
    plan: free
    region: oregon
    ipAllowList: [] # Permite acceso solo desde servicios internos (seguridad)