services:
  - type: web
    name: paso-backend
    runtime: docker
    region: oregon
    plan: starter # El plan de $7 para el servidor web sigue llamándose 'starter'
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paso-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"

databases:
  - name: paso-db
    region: oregon
    plan: basic # <--- AQUÍ ESTABA EL ERROR. Ahora es 'basic' ($7 USD aprox)
    databaseName: paso_db
    user: paso_admin
